catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBookByUserListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date
import uuid

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Horror Fiction)')

    def __str__(self):
        return self.name
    
class Language(models.Model):
    name = models.CharField(
        max_length=200, 
        help_text='Enter the book\'s natural language (e.g. English, French, Japanese, etc.)')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN', max_length=13, unique=True, 
        help_text='13 Characters <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
    )
    genre = models.ManyToManyField('Genre', help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, 
        help_text='Unique ID for this particular book across the whole library'
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = [('can_mark_returned', 'Set book as returned')]

    @property
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("catalog:author-detail", args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import BookInstance

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data
    
class RenewBookModelForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

    def clean_renewal_date(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data

catalog/views.py
import datetime

from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy

from .models import Genre, Language, Book, BookInstance, Author 
from .forms import RenewBookForm, RenewBookModelForm

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_horror_genres = Genre.objects.filter(name__icontains='horror').count()
    num_specialized_books = Book.objects.filter(title__icontains='en').count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_horror_genres': num_horror_genres,
        'num_specialized_books': num_specialized_books,
        'num_visits': num_visits
    }

    return render(request, 'catalog/index.html', context=context)

@login_required
@permission_required('catalog.can_mark_return', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookModelForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            return HttpResponseRedirect(reverse('catalog:all-borrowed'))
        
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance
    }
    return render(request, 'catalog/book_renew_librarian.html', context)

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    # queryset = Book.objects.filter(title__icontains='en')[:5]
    template_name = 'catalog/book_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.all()

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'
    queryset = Author.objects.order_by('last_name', 'first_name')
    template_name = 'catalog/author_list.html'
    paginate_by = 2

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    context_object_name = 'bookinstance_list'
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o')
        )
    
class BorrowedBookByUserListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    context_object_name = 'borrowed_books'
    template_name = 'catalog/all_borrowed_books.html'

    permission_required = 'catalog.can_mark_returned'
    
    def get_queryset(self):
        return (
            BookInstance.objects.filter(status__exact='o')
        )
    
class AuthorCreate(PermissionRequiredMixin, generic.CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '11/06/2020'}
    permission_required = 'catalog.can_mark_returned'

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('catalog:authors')

class BookCreate(CreateView):
    model = Book
    fields = '__all__'

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('catalog:books')

catalog/templates/catalog/all_borrowed_books.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if borrowed_books %}
        <ul>
            {% for borrowedbk in borrowed_books %}
                <li class="{% if borrowedbk.is_overdue %} text-danger {% endif %}">
                    <a href="{% url 'catalog:book-detail' borrowedbk.book.pk %}">{{ borrowedbk.book.title }}</a>
                    ({{ borrowedbk.due_back }}) - {{ borrowedbk.borrower.username }}
                </li>
                {% if perms.catalog.can_mark_returned %} -
                    <a href="{% url 'catalog:renew-book-librarian' borrowedbk.id %}">Renew</a>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books borrowed.</p>

    {% endif %}

{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends 'catalog/base_generic.html' %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>
    {% if author.date_of_birth %}
        <p>{{ author.date_of_birth }} - {{ author.date_of_death }}</p>
    {% endif %}
    <div style="margin:0px 0px 20px 2px">
        <h4>Books</h4>
        {% for book in author.book_set.all %}
            <p>
                <!-- <a href="{% url 'catalog:book-detail' book.id %}">{{ book.title }}</a>  -->
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> 
                <strong> ({{ book.id }})</strong>
            </p>
            <p>{{ book.summary }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <!-- <a href="{% url 'catalog:author-detail' author.id %}"> -->
                    <a href="{{ author.get_absolute_url }}">
                        {{ author.last_name}}, {{author.first_name}}
                        {% if author.birthday %} 
                            ({{ author.date_of_birth }} - {{ author.date_of_death }})
                        {% endif %}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/styles.css' %}" />
    <style>
      .siderbar-nav {
        list-style-type: none;
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'catalog:index' %}">Home</a></li>
              <li><a href="{% url 'catalog:books' %}">All books</a></li>
              <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
            </ul>
            <ul class="sidebar-nav">
              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
              {% endif %}
            </ul>
            <hr>
            <ul class="sidebar-nav">
              {% if perms.catalog.can_mark_returned %}
                <li>Staff</li>
                <li><a href="{% url 'catalog:all-borrowed' %}">All borrowed</a></li>
                <li><a href="{% url 'catalog:book-create' %}">Add New Books</a></li>
                <li><a href="{% url 'catalog:author-create' %}">Add New Authors</a></li>
              {% endif %}
              </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        {% block pagination %}
          {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
         {% endif %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/book_confirm_delete.html
{% extends 'catalog/base_generic.html' %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <!-- <p><strong>Author:</strong> <a href="{% url 'catalog:author-detail' book.author.id %}">{{ book.author }}</a></p> -->
    <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong>{{ book.genre.all|join:", " }}</p>

    <div style="margin:0px 0px 20px 2px">
        <h4>Copies</h4>
        
        {% for copy in book.bookinstance_set.all %}
            <hr />
            <p class="
                {% if copy.status == 'a' %}
                    text-success
                {% elif copy.status == 'm' %}
                    text-danger
                {% else %}
                    text-warning
                {% endif %}
            ">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
            <li>
                <!-- <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> -->
                <a href="{% url 'catalog:book-detail' book.id %}">{{ book.title }}</a>
                ({{ book.author }})
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p {% if book_instance.is_overdue %} class="text-danger" {% endif %} >
        Due date: {{ book_instance.due_back }}
    </p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
            <li class="
                {% if bookinst.is_overdue %}
                    text-danger
                {% endif %}">
                <a href="{% url 'catalog:book-detail' bookinst.book.id %}">
                    {{ bookinst.book.title }}
                </a>
                ({{ bookinst.due_back }})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Ther are no books borrowed.</p>
        
    {% endif %}

{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block title %}
    <title>My Local Library</title>
{% endblock %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Genres:</strong> {{ num_horror_genres}} </li>
    <li><strong>Specialied Books:</strong> {{ num_specialized_books }}</li>
  </ul>

  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>

{% endblock %}